services:
  bot:
    build: .
    image: telegram-utility-bot:v3
    container_name: telegram-utility-bot
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}


